export const STATUSBAR = "#B3B3B3";
export const BACKGROUND_SPLASH_START = "#FFFFFF";
export const BACKGROUND_SPLASH_END = "#E3E1E1";
export const TEXT_SMALL = "#B3B3B3";
export const GRADIENT_ARC_START = "#FF9C00";
export const GRADIENT_ARC_END = "#F05400";
export const GRADIENT_WARNING_START = "#FF001A";
export const GRADIENT_WARNING_END = "#F05400";
export const BACKGROUND_MAIN = "#FFFFFF";
export const SHADOW = "#000";
export const GRADIENT_BUTTON_START = "#FF9C00";
export const GRADIENT_BUTTON_END = "#FFCB00";
export const TEXT_bUTTON_FIRST = "#5E309D";
export const TEXT_bUTTON_SECOND = "#9A9A9A";
export const TEXT_HELP = "#FFC800";
export const TEXT_INPUT_BORDER_COLOR = "#D5D5D5";
export const PATTERN_BACKGROUND_COLOR = "#ECECEC";
export const TEXT_COLOR_TOP = "#9E9E9E";
export const TEXT_COLOR_TOP2 = "#949494";
export const BACKGROUND_MODAL = "#FFFFFF";
export const BACKGROUND_CARD= "#FFFFFF";
export const DEVIDER_COLOR = "#EBEBEB";
export const TEXT_TITLE_RESULT = "#464646";
export const BORDER_VIEW = "#E6E6E6";
export const TEXT_DISCOUNTED_PRICE = "#F87900";
export const BACKGROUND_DISCOUNT_PERSENT_START = "#FF6784";
export const BACKGROUND_DISCOUNT_PERSENT_END = "#5E309D";
export const TEXT_DISCOUNT_PERSENT = "#FFFFFF";
export const BACKGROUND_TOOLBAR = "#FFFFFF";
export const TEXT_TOOLBAR = "#8D8D8D";
export const BACKGROUND_TABBAR_RESTAURANT = "#E2E2E2";
export const TEXT_TABBAR_ACTIVE= "#B24195";
export const BACKGROUND_LIST_RESTAURANT = "#EFEFEF";
export const LIKED = "#FF3980";
export const NOT_LIKED = "#AAAAAA";
export const TEXT_GO_CART = "#FFFFFF";
export const TEXT_DRAWER_NAME = "#683030";
export const TEXT_DRAWER_MOBILE = "#BD8215";
export const BACKGROUND_CARD_WINDOW_FIRST = "#94EDFF";
export const BACKGROUND_CARD_WINDOW_SECOND = "#14D3F9";
export const PROFILE_TESTER_PAGE_TEXT = "#AFAFAF";
export const INDICATOR_TAB = "#B8B5B5";
export const HAPPY = "#4CAF50";
export const MEDDLING = "#FFB300";
export const BAD = "#F44336";
export const MAIN_ACTION_BUTTONS = "#FFC700";
export const ACTION_BUTTON_FIRST = "#389E94";
export const ACTION_BUTTON_SECOND = "#FF0060";
export const ACTION_BUTTON_THIRD = "#FF8800";
export const BUTTON_CART = "#20BF20";
export const BACKGROUND_RATE = "#F9F9F9";

export default {
    STATUSBAR,
    BACKGROUND_SPLASH_START,
    BACKGROUND_SPLASH_END,
    TEXT_SMALL,
    GRADIENT_ARC_START,
    GRADIENT_ARC_END,
    GRADIENT_WARNING_START,
    GRADIENT_WARNING_END,
    BACKGROUND_MAIN,
    SHADOW,
    GRADIENT_BUTTON_START,
    GRADIENT_BUTTON_END,
    TEXT_bUTTON_FIRST,
    TEXT_bUTTON_SECOND,
    TEXT_HELP,
    TEXT_INPUT_BORDER_COLOR,
    PATTERN_BACKGROUND_COLOR,
    TEXT_COLOR_TOP,
    TEXT_COLOR_TOP2,
    BACKGROUND_MODAL,
    DEVIDER_COLOR,
    TEXT_TITLE_RESULT,
    BORDER_VIEW,
    TEXT_DISCOUNTED_PRICE,
    BACKGROUND_DISCOUNT_PERSENT_START,
    BACKGROUND_DISCOUNT_PERSENT_END,
    TEXT_DISCOUNT_PERSENT,
    BACKGROUND_TOOLBAR,
    TEXT_TOOLBAR,
    BACKGROUND_TABBAR_RESTAURANT,
    BACKGROUND_LIST_RESTAURANT,
    TEXT_TABBAR_ACTIVE,
    LIKED,NOT_LIKED,
    TEXT_GO_CART,
    TEXT_DRAWER_NAME,
    TEXT_DRAWER_MOBILE,
    BACKGROUND_CARD_WINDOW_FIRST,
    BACKGROUND_CARD_WINDOW_SECOND,
    PROFILE_TESTER_PAGE_TEXT,
    INDICATOR_TAB,
    BACKGROUND_CARD,
    HAPPY,
    MEDDLING,
    BAD,
    MAIN_ACTION_BUTTONS,
    ACTION_BUTTON_FIRST,
    ACTION_BUTTON_SECOND,
    ACTION_BUTTON_THIRD,
    BUTTON_CART,
    BACKGROUND_RATE
};